In [6]:
# Recursive Feature Elimination
import pandas as pd
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score

df = pd.read_csv('./simulated_data.csv')
X = df.iloc[:, 1:50]
Y = df.loc[:, 'nograd']
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.3, random_state=0)

In [20]:
model = LogisticRegression()
rfe = RFE(model, 25)
X_train_trans = rfe.fit_transform(X_train, y_train)
X_test_trans = rfe.transform(X_test) # Note: Using transform here.
print X_trans.shape

(700, 3)

In [21]:
log_reg = LogisticRegression().fit(X_train_trans, y_train)
y_pred = log_reg.predict(X_test_trans)
pred_test_values = pd.DataFrame( {'y_pred': y_pred, 'y_test': y_test} )
true_and_false_positives = pred_test_values.loc[ pred_test_values['y_test'] == 1 ]

true_and_false_positives

     y_pred  y_test
906       0       1
760       0       1
366       0       1
783       0       1
531       0       1
389       0       1
601       0       1
108       0       1
785       1       1
317       0       1
780       0       1
529       0       1
54        0       1
975       0       1
999       0       1
467       0       1
834       0       1
679       0       1
814       0       1
518       0       1
113       0       1
40        0       1
18        0       1
200       0       1
944       1       1
50        0       1
700       0       1
998       0       1